default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: hateblocker_development
  username: postgres
  password:

test:
  <<: *default
  host: db
  database: hateblocker_test
  username: postgres
  password:

production:
  <<: *default
  database: hateblocker_production
  username: hateblocker
  password: <%= ENV['HATEBLOCKER_DATABASE_PASSWORD'] %>
